import type { SurfaceManifest } from "@preacherman/surface-skin";

export type FigmaScreenNodeType = "FRAME" | "SECTION";
export type FigmaScreenImplementationStatus = "implemented" | "pending";
export type FigmaScreenQaStatus = "accepted" | "in-progress" | "pending";

export interface FigmaScreenRegistryEntry {
  readonly screenId: string;
  readonly pageId: string;
  readonly pageName: string;
  readonly screenNodeId: string;
  readonly nodeType: FigmaScreenNodeType;
  readonly frameName: string;
  readonly width: 1440;
  readonly height: 900;
  readonly order: number;
  readonly is1440x900: true;
  readonly domain: string;
  readonly backendScreenIndex: string;
  readonly userFlow: string;
  readonly expectedEntry: string;
  readonly expectedExit: string;
  readonly implementationStatus: FigmaScreenImplementationStatus;
  readonly qaStatus: FigmaScreenQaStatus;
  readonly manifest?: SurfaceManifest;
}

type ScreenInput = Omit<FigmaScreenRegistryEntry, "width" | "height" | "is1440x900">;

function screen(input: ScreenInput): FigmaScreenRegistryEntry {
  return { ...input, width: 1440, height: 900, is1440x900: true };
}

const commonHomeEntry = "Open from the accepted Home surface or the immediately preceding Home state.";
const commonHomeExit = "Continue within the Home flow or return to the accepted Home surface.";
const commonWorkspaceEntry = "Open from Home conversation through Turn into Task.";
const commonWorkspaceExit = "Continue to the next task state or return to Home.";
const pendingQa = "pending" as const;

export const pdfReconciliation = "PDF 55页待补充核对" as const;

export const figmaScreenRegistry: ReadonlyArray<FigmaScreenRegistryEntry> = [
  screen({ screenId: "figma-281-538", pageId: "281:537", pageName: "home", screenNodeId: "281:538", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 0, domain: "Home 与对话", backendScreenIndex: "SCR-001 (backend Page ID 2003:38 differs from current Figma)", userFlow: "FLOW-02 / FLOW-03 / FLOW-10", expectedEntry: "Restore the authenticated session with a Current State.", expectedExit: "Open Status, Current State, chat, or a primary navigation destination.", implementationStatus: "implemented", qaStatus: "accepted", manifest: { surfaceType: "workspace", schemaVersion: 1, surfaceId: "figma-281-538", title: "Page 6 工作区 / conversation workspace" } }),
  screen({ screenId: "figma-287-637", pageId: "287:636", pageName: "home点击status", screenNodeId: "287:637", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 1, domain: "Home 与对话", backendScreenIndex: "SCR-002", userFlow: "FLOW-02", expectedEntry: "Click Status on Home.", expectedExit: "Close the State Trace overview or continue to Monitor detail.", implementationStatus: "implemented", qaStatus: "accepted", manifest: { surfaceType: "home", schemaVersion: 1, surfaceId: "figma-287-637", title: "home点击status" } }),
  screen({ screenId: "figma-287-714", pageId: "287:713", pageName: "home点击current state", screenNodeId: "287:714", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 2, domain: "Home 与对话", backendScreenIndex: "SCR-004", userFlow: "FLOW-02", expectedEntry: "Click Current State on Home.", expectedExit: "Open the Current State detail or return to Home.", implementationStatus: "implemented", qaStatus: "accepted", manifest: { surfaceType: "home", schemaVersion: 1, surfaceId: "figma-287-714", title: "home点击current state" } }),
  screen({ screenId: "figma-219-3", pageId: "219:2", pageName: "home点击current state详情", screenNodeId: "219:3", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 3, domain: "Home 与对话", backendScreenIndex: "SCR-005", userFlow: "FLOW-02", expectedEntry: "Open Current State detail from the Home summary.", expectedExit: "Return to chat or enter Mount Skill, Edit State, Profile, Test, or Ledger.", implementationStatus: "implemented", qaStatus: "accepted", manifest: { surfaceType: "home", schemaVersion: 1, surfaceId: "figma-219-3", title: "home点击current state详情" } }),
  screen({ screenId: "figma-281-374", pageId: "281:373", pageName: "home点击人模对话", screenNodeId: "281:374", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 4, domain: "Home 与对话", backendScreenIndex: "SCR-006", userFlow: "FLOW-03", expectedEntry: "Hover or focus the State figure on Home.", expectedExit: "Click the State figure to open full conversation.", implementationStatus: "implemented", qaStatus: "accepted", manifest: { surfaceType: "home", schemaVersion: 1, surfaceId: "figma-281-374", title: "home点击人模对话" } }),
  screen({ screenId: "figma-32-2", pageId: "7:102", pageName: "home对话", screenNodeId: "32:2", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 5, domain: "Home 与对话", backendScreenIndex: "SCR-007", userFlow: "FLOW-03", expectedEntry: "Click the State figure or conversation entry.", expectedExit: "Send a prompt, turn the conversation into a task, or return to Home.", implementationStatus: "implemented", qaStatus: "accepted", manifest: { surfaceType: "home", schemaVersion: 1, surfaceId: "figma-32-2", title: "home对话" } }),
  screen({ screenId: "figma-412-728", pageId: "100:166", pageName: "home对话hover", screenNodeId: "412:728", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 6, domain: "Home 与对话", backendScreenIndex: "SCR-008 (backend name: home对话发送后)", userFlow: "FLOW-03", expectedEntry: "Send the designed product-opportunities prompt from full conversation.", expectedExit: "Continue the conversation, retry, or turn it into a task.", implementationStatus: "implemented", qaStatus: "accepted", manifest: { surfaceType: "home", schemaVersion: 1, surfaceId: "figma-412-728", title: "home对话hover" } }),
  screen({ screenId: "figma-416-746", pageId: "416:745", pageName: "home对话hover导出对话记录（待完成", screenNodeId: "416:746", nodeType: "FRAME", frameName: "Page 6 工作区 / conversation workspace", order: 7, domain: "Home 与对话", backendScreenIndex: "SCR-010", userFlow: "FLOW-03", expectedEntry: commonHomeEntry, expectedExit: commonHomeExit, implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-38-2", pageId: "7:106", pageName: "工作区", screenNodeId: "38:2", nodeType: "FRAME", frameName: "Page 10 / Preserve State Composer", order: 8, domain: "工作区与任务", backendScreenIndex: "SCR-011", userFlow: "FLOW-04", expectedEntry: commonWorkspaceEntry, expectedExit: commonWorkspaceExit, implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-493-653", pageId: "493:469", pageName: "工作区 等待中", screenNodeId: "493:653", nodeType: "SECTION", frameName: "Page 10 / Preserve State Composer", order: 9, domain: "工作区与任务", backendScreenIndex: "SCR-012", userFlow: "FLOW-04", expectedEntry: commonWorkspaceEntry, expectedExit: commonWorkspaceExit, implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-502-660", pageId: "502:659", pageName: "工作区 任务完成后", screenNodeId: "502:660", nodeType: "SECTION", frameName: "工作区2 / Task Completed", order: 10, domain: "工作区与任务", backendScreenIndex: "SCR-013", userFlow: "FLOW-04", expectedEntry: commonWorkspaceEntry, expectedExit: commonWorkspaceExit, implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-503-729", pageId: "503:728", pageName: "工作区 任务完成后  2", screenNodeId: "503:729", nodeType: "SECTION", frameName: "工作区2 / Task Completed", order: 11, domain: "工作区与任务", backendScreenIndex: "SCR-014", userFlow: "FLOW-04", expectedEntry: commonWorkspaceEntry, expectedExit: commonWorkspaceExit, implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-503-797", pageId: "503:796", pageName: "preacherman lab (adjust state) ", screenNodeId: "503:797", nodeType: "FRAME", frameName: "Adjust This State", order: 12, domain: "State Lab", backendScreenIndex: "SCR-015", userFlow: "FLOW-05", expectedEntry: "Open Adjust State from a task or test result.", expectedExit: "Save a draft or continue to State Test.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-112-214", pageId: "112:213", pageName: "preacherman lab", screenNodeId: "112:214", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 13, domain: "State Lab", backendScreenIndex: "SCR-016", userFlow: "FLOW-06", expectedEntry: "Open State Lab.", expectedExit: "Create, adjust, activate, or test a State.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-412-551", pageId: "412:382", pageName: "preacherman lab 2", screenNodeId: "412:551", nodeType: "SECTION", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 14, domain: "State Lab", backendScreenIndex: "SCR-017", userFlow: "FLOW-06", expectedEntry: "Continue from State Lab.", expectedExit: "Continue the create-State flow.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-412-565", pageId: "412:564", pageName: "preacherman lab 2 hover", screenNodeId: "412:565", nodeType: "SECTION", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 15, domain: "State Lab", backendScreenIndex: "SCR-018", userFlow: "FLOW-06", expectedEntry: "Hover the designed State Lab control.", expectedExit: "Continue the create-State flow.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-20-72", pageId: "7:103", pageName: "preacherman lab (create state)", screenNodeId: "20:72", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 16, domain: "State Lab", backendScreenIndex: "SCR-019", userFlow: "FLOW-06", expectedEntry: "Choose Create State in State Lab.", expectedExit: "Use recommended Skills or continue to testing.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-487-194", pageId: "250:2", pageName: "state test hover前", screenNodeId: "487:194", nodeType: "SECTION", frameName: "State Test / task setup", order: 17, domain: "State Test", backendScreenIndex: "SCR-021", userFlow: "FLOW-08", expectedEntry: "Open State Test with a State version.", expectedExit: "Run the test.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-493-374", pageId: "493:373", pageName: "state test  hover后", screenNodeId: "493:374", nodeType: "SECTION", frameName: "State Test / task setup", order: 18, domain: "State Test", backendScreenIndex: "SCR-022", userFlow: "FLOW-08", expectedEntry: "Hover the Run Test state.", expectedExit: "Run the test.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-487-196", pageId: "487:195", pageName: "state test  2", screenNodeId: "487:196", nodeType: "SECTION", frameName: "State Test / task setup", order: 19, domain: "State Test", backendScreenIndex: "SCR-023", userFlow: "FLOW-08", expectedEntry: "Start a TestRun.", expectedExit: "Continue to completed test results.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-487-372", pageId: "487:286", pageName: "state test  3", screenNodeId: "487:372", nodeType: "FRAME", frameName: "State Test / completed result", order: 20, domain: "State Test", backendScreenIndex: "SCR-024", userFlow: "FLOW-08", expectedEntry: "Complete a TestRun.", expectedExit: "Preview, export, rerun, adjust, or use the result.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-166-233", pageId: "166:232", pageName: "preacherman lab skills页面", screenNodeId: "166:233", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 21, domain: "Skills 生命周期", backendScreenIndex: "SCR-025", userFlow: "FLOW-07", expectedEntry: "Open Skills from State Lab.", expectedExit: "Create, import, evolve, validate, or publish a Skill.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-112-3", pageId: "112:2", pageName: "preacherman lab skills页面 空白创建1", screenNodeId: "112:3", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 22, domain: "Skills 生命周期", backendScreenIndex: "SCR-026", userFlow: "FLOW-07", expectedEntry: "Start Create Skill.", expectedExit: "Continue the Skill authoring steps.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-344-497", pageId: "344:496", pageName: "preacherman lab skills页面 空白创建2", screenNodeId: "344:497", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 23, domain: "Skills 生命周期", backendScreenIndex: "SCR-027", userFlow: "FLOW-07", expectedEntry: "Continue Create Skill.", expectedExit: "Continue the Skill authoring steps.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-344-1159", pageId: "344:1158", pageName: "preacherman lab skills页面 空白创建3", screenNodeId: "344:1159", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 24, domain: "Skills 生命周期", backendScreenIndex: "SCR-028", userFlow: "FLOW-07", expectedEntry: "Continue Create Skill.", expectedExit: "Continue the Skill authoring steps.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-352-1993", pageId: "352:1992", pageName: "preacherman lab skills页面 空白创建4", screenNodeId: "352:1993", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 25, domain: "Skills 生命周期", backendScreenIndex: "SCR-029", userFlow: "FLOW-07", expectedEntry: "Continue Create Skill.", expectedExit: "Continue the Skill authoring steps.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-352-3020", pageId: "352:3019", pageName: "preacherman lab skills页面 空白创建5", screenNodeId: "352:3020", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 26, domain: "Skills 生命周期", backendScreenIndex: "SCR-030", userFlow: "FLOW-07", expectedEntry: "Continue Create Skill.", expectedExit: "Save, validate, or publish the Skill.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-166-4", pageId: "166:3", pageName: "preacherman lab skills页面 开发者模式", screenNodeId: "166:4", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 27, domain: "Skills 生命周期", backendScreenIndex: "SCR-031", userFlow: "FLOW-07", expectedEntry: "Switch Skill authoring to Developer Mode.", expectedExit: "Return to visual mode or validate the Skill.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-166-400", pageId: "166:399", pageName: "preacherman lab skills页面 重构1", screenNodeId: "166:400", nodeType: "FRAME", frameName: "Evolve Skill / Import Skill", order: 28, domain: "Skills 生命周期", backendScreenIndex: "SCR-032", userFlow: "FLOW-07", expectedEntry: "Choose Evolve Skill.", expectedExit: "Continue Skill evolution.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-363-3", pageId: "363:2", pageName: "preacherman lab skills页面 重构2", screenNodeId: "363:3", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 29, domain: "Skills 生命周期", backendScreenIndex: "SCR-033", userFlow: "FLOW-07", expectedEntry: "Continue Skill evolution.", expectedExit: "Continue Skill evolution.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-393-3", pageId: "393:2", pageName: "preacherman lab skills页面 重构3", screenNodeId: "393:3", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 30, domain: "Skills 生命周期", backendScreenIndex: "SCR-034", userFlow: "FLOW-07", expectedEntry: "Continue Skill evolution.", expectedExit: "Continue Skill evolution.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-436-3", pageId: "436:2", pageName: "preacherman lab skills页面 重构5", screenNodeId: "436:3", nodeType: "FRAME", frameName: "Evolve Skill / Publish Skill", order: 31, domain: "Skills 生命周期", backendScreenIndex: "SCR-035", userFlow: "FLOW-07", expectedEntry: "Open Publish Skill.", expectedExit: "Publish or return to the Skill draft.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-404-2", pageId: "393:204", pageName: "preacherman lab skills页面 重构导出", screenNodeId: "404:2", nodeType: "FRAME", frameName: "Generate Version / export format modal state", order: 32, domain: "Skills 生命周期", backendScreenIndex: "SCR-036", userFlow: "FLOW-07", expectedEntry: "Choose Skill export.", expectedExit: "Generate or cancel the export.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-409-379", pageId: "334:28", pageName: "preacherman lab skills页面 导入验证", screenNodeId: "409:379", nodeType: "SECTION", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 33, domain: "Skills 生命周期", backendScreenIndex: "SCR-037", userFlow: "FLOW-07", expectedEntry: "Import a Skill package.", expectedExit: "Validate or cancel the import.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-22-197", pageId: "7:104", pageName: "skills test", screenNodeId: "22:197", nodeType: "FRAME", frameName: "Page 8 / Test Bench", order: 34, domain: "Skills 生命周期", backendScreenIndex: "SCR-039", userFlow: "FLOW-07", expectedEntry: "Run Skill validation.", expectedExit: "Return to the Skill draft or publish.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-53-2", pageId: "7:105", pageName: "state gallery", screenNodeId: "53:2", nodeType: "FRAME", frameName: "State Match", order: 35, domain: "State 生态与治理", backendScreenIndex: "SCR-040", userFlow: "FLOW-09", expectedEntry: "Open State Gallery.", expectedExit: "Open State Passport or try a State with a task.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-476-192", pageId: "7:107", pageName: "state passport", screenNodeId: "476:192", nodeType: "SECTION", frameName: "State Passport", order: 36, domain: "State 生态与治理", backendScreenIndex: "SCR-041", userFlow: "FLOW-09", expectedEntry: "Choose a State in Gallery.", expectedExit: "Install, test in Sandbox, or return to Gallery.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-258-2", pageId: "7:108", pageName: "state ledger", screenNodeId: "258:2", nodeType: "FRAME", frameName: "State Ledger / reference screen", order: 37, domain: "State 生态与治理", backendScreenIndex: "SCR-042", userFlow: "FLOW-10", expectedEntry: "Open Ledger from Home or Current State detail.", expectedExit: "Compare, branch, restore to draft, or return Home.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-514-202", pageId: "514:201", pageName: "state status 统一", screenNodeId: "514:202", nodeType: "SECTION", frameName: "State Monitor", order: 38, domain: "State 生态与治理", backendScreenIndex: "No direct 55-screen index match (new unified Figma page)", userFlow: "FLOW-02 / FLOW-10", expectedEntry: "Open unified Status from Home.", expectedExit: "Return Home or open monitor detail.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-514-116", pageId: "514:2", pageName: "state status", screenNodeId: "514:116", nodeType: "SECTION", frameName: "State Monitor", order: 39, domain: "State 生态与治理", backendScreenIndex: "SCR-043", userFlow: "FLOW-10", expectedEntry: "Open Status from Home.", expectedExit: "Return Home or expand a monitor card.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-514-117", pageId: "503:1178", pageName: "state status 详情", screenNodeId: "514:117", nodeType: "SECTION", frameName: "State Monitor", order: 40, domain: "State 生态与治理", backendScreenIndex: "SCR-003", userFlow: "FLOW-02", expectedEntry: "Open Monitor detail from Status.", expectedExit: "Return to the Home monitor.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-523-3", pageId: "523:2", pageName: "state status 详情 2", screenNodeId: "523:3", nodeType: "SECTION", frameName: "State Monitor", order: 41, domain: "State 生态与治理", backendScreenIndex: "SCR-044 (name/ID differs; requires product reconciliation)", userFlow: "FLOW-10", expectedEntry: "Open alternate Monitor detail.", expectedExit: "Return to the Home monitor.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-166-602", pageId: "166:601", pageName: "preacherman lab skills页面5", screenNodeId: "166:602", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 42, domain: "Skills 生命周期", backendScreenIndex: "SCR-045", userFlow: "ARCHIVED", expectedEntry: "Archived design reference only.", expectedExit: "No product route.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-166-800", pageId: "166:799", pageName: "preacherman lab skills页面6", screenNodeId: "166:800", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 43, domain: "Skills 生命周期", backendScreenIndex: "SCR-046", userFlow: "ARCHIVED", expectedEntry: "Archived design reference only.", expectedExit: "No product route.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-189-1032", pageId: "189:1031", pageName: "preacherman lab skills页面7", screenNodeId: "189:1032", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 44, domain: "Skills 生命周期", backendScreenIndex: "SCR-047", userFlow: "ARCHIVED", expectedEntry: "Archived design reference only.", expectedExit: "No product route.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-189-1263", pageId: "189:1262", pageName: "preacherman lab skills页面8", screenNodeId: "189:1263", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 45, domain: "Skills 生命周期", backendScreenIndex: "SCR-048", userFlow: "ARCHIVED", expectedEntry: "Archived design reference only.", expectedExit: "No product route.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-189-1613", pageId: "189:1612", pageName: "preacherman lab skills页面9", screenNodeId: "189:1613", nodeType: "FRAME", frameName: "Page 7 preacherman lab / state lab rebuilt", order: 46, domain: "Skills 生命周期", backendScreenIndex: "SCR-049", userFlow: "ARCHIVED", expectedEntry: "Archived design reference only.", expectedExit: "No product route.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-7-11", pageId: "7:2", pageName: "Page 1 欢迎页", screenNodeId: "7:11", nodeType: "FRAME", frameName: "Desktop - 1", order: 47, domain: "登录与引导", backendScreenIndex: "SCR-050", userFlow: "FLOW-01", expectedEntry: "Launch without a valid session.", expectedExit: "Choose login or account creation.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-1-2", pageId: "0:1", pageName: "page 2 登录页", screenNodeId: "1:2", nodeType: "FRAME", frameName: "Desktop - 1", order: 48, domain: "登录与引导", backendScreenIndex: "SCR-051", userFlow: "FLOW-01", expectedEntry: "Choose login from Welcome.", expectedExit: "Open APP Home or account creation.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-7-74", pageId: "1:3", pageName: "Page 3 账号创建页", screenNodeId: "7:74", nodeType: "FRAME", frameName: "Desktop - 1", order: 49, domain: "登录与引导", backendScreenIndex: "SCR-052", userFlow: "FLOW-01", expectedEntry: "Choose account creation.", expectedExit: "Continue to profile completion.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-7-99", pageId: "7:98", pageName: "Page 4 完善个人信息页", screenNodeId: "7:99", nodeType: "FRAME", frameName: "Desktop - 1", order: 50, domain: "登录与引导", backendScreenIndex: "SCR-053", userFlow: "FLOW-01", expectedEntry: "Create an account.", expectedExit: "Save the profile and open APP Home.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-8-2", pageId: "7:101", pageName: "Page 5 APP首页", screenNodeId: "8:2", nodeType: "FRAME", frameName: "Desktop - 1", order: 51, domain: "登录与引导", backendScreenIndex: "SCR-054", userFlow: "FLOW-01", expectedEntry: "Complete login or profile setup.", expectedExit: "Open the main Monitor/Home experience.", implementationStatus: "pending", qaStatus: pendingQa }),
  screen({ screenId: "figma-94-3", pageId: "94:2", pageName: "工作区 任务完成后", screenNodeId: "94:3", nodeType: "FRAME", frameName: "Page 6 工作区3 / task brief workspace", order: 52, domain: "工作区与任务", backendScreenIndex: "SCR-055 (archived / not delivered)", userFlow: "ARCHIVED", expectedEntry: "Archived design reference only.", expectedExit: "No product route.", implementationStatus: "pending", qaStatus: pendingQa }),
];

export const implementedFigmaScreens = figmaScreenRegistry.filter(
  (entry) => entry.implementationStatus === "implemented",
);

export function findFigmaScreen(screenId: string | null | undefined) {
  return figmaScreenRegistry.find((entry) => entry.screenId === screenId);
}
